### ISSUE TITLE
 Update to 1.1?

### ISSUE THREAD

**Issue by Two-Tone** [TheWireLord/ConduitDeconstructMod#2]
Rimworld 1.1 is out and mods need to update to be compatible.  Is there any intent on updating this mod?

Also, when you update there is no longer a reason to submit the update as a new workshop item.  Instead you can just use the game's multi-version support.  [The Harmony dev even made an easy to follow tutorial.](https://gist.github.com/pardeike/08ff826bf40ee60452f02d85e59f32ff)

**Comment by TheWireLord** [comment]
Working on a new update as we speak! Update should be out later today at https://steamcommunity.com/sharedfiles/filedetails/?id=838336462 as well as here on GitHub of course.

**Comment by TheWireLord** [comment]
Update is LIVE!
